# For more information: https://laravel.com/docs/sail
version: '3'
services:
  web:
    build:
        context: ./vendor/laravel/sail/runtimes/8.0
        dockerfile: Dockerfile
        args:
            WWWGROUP: '${WWWGROUP}'
    image: sail-8.0/app
    ports:
        - '${APP_PORT:-80}:80'
    environment:
        WWWUSER: '${WWWUSER}'
        LARAVEL_SAIL: 1
    volumes:
        - '.:/var/www/html'
    networks:
      quickcount:
        ipv4_address: 172.31.0.51
    depends_on:
            - mysql

  mysql:
    image: 'mysql:8.0'
    ports:
        - '${FORWARD_DB_PORT:-33060}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - 'sailmysql:/var/lib/mysql'
    networks:
      quickcount:
        ipv4_address: 172.31.0.52

networks:
  quickcount:
    external: true
volumes:
    sailmysql:
        driver: local
#     sailredis:
#         driver: local
